grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 4
    verbose: 2

model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      fit_intercept: True

    search_param_grid:
      penalty:
      - l2
      fit_intercept:
      - True
      # - False

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
      min_samples_leaf: 1
    search_param_grid:
      n_estimators:
      - 1800
      # - 2000
      min_samples_leaf:
      - 6
      # - 8
      max_features:
      - auto
      # - sqrt
      # - log2
      max_depth:
      - 10
      # - 120
      min_samples_split:
      - 5
      # - 10
      criterion:
      - entropy
      # - gini



