columns:
  - A1_Score: int
  - A2_Score: int
  - A3_Score: int
  - A4_Score: int
  - A5_Score: int
  - A6_Score: int
  - A7_Score: int
  - A8_Score: int
  - A9_Score: int
  - A10_Score: int
  - age: float
  - gender: category
  - ethnicity: category
  - jaundice: category
  - austim: category
  - contry_of_res: category
  - used_app_before: category
  - result: float
  - relation: category
  - Class/ASD: int


numerical_columns:
  - age
  - result

categorical_columns:
  - gender
  - ethnicity
  - jaundice
  - austim
  - contry_of_res
  - used_app_before
  - relation


drop_columns:
  - age_desc
  - ID

target_column:
  - Class/ASD

label_encoding:
  - ageGroup

one_hot_encoding:
  - gender
  - ethnicity
  - jaundice
  - austim
  - contry_of_res
  - used_app_before
  - relation

median_impute:
  - result
  - age

mode_impute:
  - A1_Score
  - A2_Score
  - A3_Score
  - A4_Score
  - A5_Score
  - A6_Score
  - A7_Score
  - A8_Score
  - A9_Score
  - A10_Score



